project:
  type: book
  
book:
  title: "Dyadic Structural Equation Modeling in R"
  author: "John Kitchener Sakaluk"
  date: "today"
  cover-image: cover.png
  search: true
  repo-url: https://github.com/jsakaluk/Dyadic-Structural-Equation-Modeling-in-R/
  repo-actions: [edit, issue, source]
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
  chapters:
    - index.qmd
    - support.qmd
    - about.qmd
    - acknowledgements.qmd
    - part: "Act I: Getting Started"
      chapters:
      - intro.qmd
      - bigpicture.qmd
      - dyadicdatastructure.qmd
      - latentvariabletheory.qmd
    - part: "Act II: SEM Fundamentals"
      chapters:
        - models.qmd
        - identification.qmd
        - estimation.qmd
        - modelfitindexes.qmd
        - modelcomparisonstrategies.qmd
        - nondyadicexample.qmd
    - part: "Intermission 1: Meet Your Dyadic Models"
      chapters:
        - dyadicmodels.qmd
    - part: "Act III: Uni-Construct Cross-Sectional Dyadic Models"
      chapters:
        - onefactor.qmd
        - twofactor.qmd
        - bifactor.qmd
        - hierarchical.qmd
        - causal.qmd
        - invariance.qmd
        - choosing.qmd
    - part: "Act IV: Bi-Construct Cross-Sectional Dyadic Models"
      chapters:
        - couple.qmd
        - apim.qmd
        - bifactorstructural.qmd
        - commonfate.qmd
        - mix.qmd
    - part: "Intermission 2: What Is '(In)distinguishability'?"
      chapters:
        - indistinguishable.qmd
    - part: "Act V: Advanced Applications of Dyadic SEM"
      chapters:
        - thirdvarmods.qmd
        - multigroup.qmd
        - longitudinal.qmd
        - defa.qmd
        - montecarlo.qmd
        - software.qmd
    - part: "Fin"
      chapters:
        - conclusion.qmd
    - references.qmd
  appendices:
    - sufficient_R.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    footer: "Licensed under [CC BY-NC-ND 4.0](https://creativecommons.org/licenses/by-nc-nd/4.0/)."
  pdf:
    documentclass: scrreprt
    include-in-header: |
      Licensed under Creative Commons BY-NC-ND 4.0
execute:
  freeze: auto



